Autotest_MVC_2/Controllers/QuestionController.cs
using Auto_test.Library.Models.QuestionModels;
using Auto_test.Library.Models.Tickets;
using Auto_test.Library.Models.UserModels;
using Autotest_MVC_2.Services.QuestionServices;
using Autotest_MVC_2.Services.UserServices;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Collections.Generic;

namespace Autotest_MVC_2.Controllers;

public class QuestionController : Controller
{
    private readonly UserService _userService;

    private readonly QuestionService _questionService;


    public QuestionController(UserService userService, QuestionService questionService)
    {
        _userService = userService;
        _questionService = questionService; ;
    }

    public IActionResult ShowTickets()
    {
        var user = _userService.GetCurrentUserAndTickets(HttpContext);

        if (user != null)
        {
            return View(user);
        }

        return RedirectToAction("IsRegister", "Home");
    }

    public IActionResult Exam()
    {
        var user = _userService.GetCurrentUserAndTickets(HttpContext);

        if (user == null)
            return RedirectToAction("IsRegister", "Home");

        user.IsExam = true;
        _userService.DbContext.SaveChanges();
        return View(user);
    }

    
    public IActionResult StartTicket(int ticketIndex)
    {
        var user = _userService.GetCurrentUserAndTickets(HttpContext);

        if (user == null)
            return RedirectToAction("IsRegister", "Home");

        if (user.UserTickets?.Count <= ticketIndex)
            return RedirectToAction("Index", "Home");
              
        if(user.IsExam)
            user.ExamCurrentTicketIndex = ticketIndex;

        user.CurrentTicketIndex = ticketIndex;
       
        var ticket = user.UserTickets?.FirstOrDefault(x => x.TicketIndex ==  ticketIndex);

        if (ticket != null)
        {
            ticket.CreateDateTime = DateTime.Now;

            user.CurrentTicket = ticket;

            user.CurrentTicket.CreateDateTime = DateTime.Now;
            _userService.DbContext.SaveChanges();
        }
        else
        {
            return RedirectToAction("Index", "Home");
        }

        return RedirectToAction(
            nameof(GetQuestion), new { questionId = user.CurrentTicket.StarQuestionIndex });
    }

    public async Task<IActionResult> GetQuestion(int questionId, int? choicesIndex = null)
    {
        var user = _userService.GetCurrentUserAndTickets(HttpContext);

        if (user == null)
            return RedirectToAction("IsRegister", "Home");

        if (questionId > user.CurrentTicketIndex * 10 + 10)
            return RedirectToAction(nameof(Result));

        if (user.Language is "rus" or "uzkiril")
            await _questionService.GetAllQuestionsAsync(user.Language!);

        var question = _questionService.Questions!.FirstOrDefault(t => t.Id == questionId);

        if (question == null)
            RedirectToAction("ShowTickets");

        ViewBag.Question = question!;
        ViewBag.IsAnswer = choicesIndex != null;

        if (choicesIndex is not null)
        {
            var ticketAnswer = new TicketQuestionAnswer
            {
                UserId = user.UserId,
                ChoiceIndex = choicesIndex.Value,
                QuestionIndex = questionId,
                CorrectAnswerIndex = question!.Choices!.IndexOf(
                    question.Choices.First(answer => answer.Answer))
            };

            user.CurrentTicket!.TicketAnswers!.Add(ticketAnswer);

            _userService.DbContext.TicketQuestionAnswers!.Add(ticketAnswer);
            _userService.DbContext.SaveChanges();

            ViewBag.TicketAnswer = ticketAnswer;
        }

        if (user.CurrentTicket!.QuestionsCount == user.CurrentTicket.TicketAnswers!.Count)
        {
            user.IsCompletedTicketCount++;
            user.TotalCorrectAnswerCount += user.CurrentTicket.TicketAnswers.Count(a=> a.IsCorrectAnswer);
            _userService.DbContext.SaveChanges();
        }

        return View(user);
    }

    public IActionResult Result()
    {
        var user = _userService.GetCurrentUserAndTickets(HttpContext);
        if (user == null)
            return RedirectToAction("IsRegister", "Home");

        ViewBag.IsExam = user.IsExam;
        user.IsExam = false;
        user.ExamCurrentTicketIndex = -1;
        _userService.DbContext.SaveChanges();

        return View(user);
    }

    public IActionResult DeleteExamData()
    {
        var user = _userService.GetCurrentUser(HttpContext);

        if (user == null)
            return RedirectToAction("IsRegister", "Home");

        user.IsExam = false;
        user.ExamCurrentTicketIndex = -1;
        _userService.DbContext.SaveChanges();

        return RedirectToAction("Index", "Home");
    }

    public IActionResult RemoveTicketAnswer()
    {
        var user = _userService.GetCurrentUserAndTickets(HttpContext);

        if (user == null)
            return RedirectToAction("SignUp", "Registration");

        user.IsCompletedTicketCount--;
        var ticket = user.CurrentTicket;

        _userService.DbContext.TicketQuestionAnswers!.RemoveRange(ticket.TicketAnswers);
        _userService.DbContext.AllUsers?.Update(user);
        _userService.DbContext.SaveChanges();

        return RedirectToAction(
            nameof(GetQuestion), new { questionId = ticket.StarQuestionIndex });
    }

    public IActionResult EditUserQuestionLanguage()
    {

        return RedirectToAction(nameof(ShowTickets));
    }



    public async Task<IActionResult> EditLanguage(string language)
    {
        var user = _userService.GetCurrentUser(HttpContext);

        if (user == null)
            return RedirectToAction("SignUp", "Registration");

        user.Language = language;
        _userService.DbContext.SaveChanges();

        return RedirectToAction(nameof(ShowTickets));
    }

}

Autotest_MVC_2/Views/Question/Exam.cshtml
@{
    ViewData["Title"] = "Exam";
}

@model Auto_test.Library.Models.UserModels.User

<style>
    .all-button {
        size: A4;
        text-align: center;
        font-weight: bold;
        background-color: red;
        width: auto;
        color: antiquewhite;
        border: 3px solid transparent;
        transition: 0.5s;
    
        padding: 13px 20px;
        border-radius: 20px 0 20px 0;
    }
    .all-button:hover {
        color: black;
        padding: 13px 20px;
        border: 3px solid red;
        transition: 0.5s;
        cursor: pointer;
    }
    .all-button1 {
        size: A4;
        text-align: center;
        font-weight: bold;
        background-color: chartreuse;
        color: crimson;
        border: 3px solid transparent;
        transition: 0.5s;
        width: auto;
        padding: 13px 20px;
        border-radius: 20px 0 20px 0;
    }
    .all-button1:hover {
        color: black;
        padding: 13px 20px;
        border: 3px solid red;
        transition: 0.5s;
        cursor: pointer;
    }

    .colorr{
         color: antiquewhite;
         text-align: center;
    }

</style>

<h1 class="colorr" style="color: antiquewhite"> Xurmatli <span style="color: lawngreen">@Model.UserName</span> </h1>
<h3 class="colorr" style="color: antiquewhite">  <span style="color: crimson">Autotest_ASR</span>  imtihonini topshirishga tayyormisiz!</h3>

<p style="color: antiquewhite; width: auto">Eslatma ushbu imtihonda sizga 10 ta savol beriladi, 
    Imtihondan o'tish uchun siz <span style="color: gold"> 8 tadan ortiq to'g'ri javob </span>  berishingiz kerak bo'ladi, 
    Sizga imtihonda omad tilaymiz :)</p>

@{
    var randomNumber = new Random().Next(0, 71);

    if (Model.ExamCurrentTicketIndex != -1)
    {
        <form 
            asp-controller="Question" 
            asp-action="StartTicket" 
            asp-route-ticketIndex="@Model.ExamCurrentTicketIndex">
            <button type="submit" class="all-button">Tugatilmagan testni davom etish </button>
        </form>
        <br/>

        <form 
            asp-controller="Question" 
            asp-action="DeleteExamData">
            <button type="submit" class="all-button">Imtihonni to'xtatish</button>
        </form>
        <br/>
    }

    <form 
        asp-controller="Question" 
        asp-action="StartTicket" 
        asp-route-ticketIndex="@randomNumber">
        <button type="submit" class="all-button1">Yangi test imtihoni</button>
    </form>
}


<div class="d-flex">
    <img
        src="http://themes.potenzaglobalsolutions.com/html/cardealer/revolution/assets/e13ec-06-audi-s2.png"
        alt=""
        class="w-50 imgss"/>
    <img
        src="http://themes.potenzaglobalsolutions.com/html/cardealer/revolution/assets/4f45e-07-bmw-s2.png"
        alt=""
        class="w-50 imgss"/>

    <!-- <img src="http://themes.potenzaglobalsolutions.com/html/cardealer/images/loader.gif" alt=""> -->
</div>

Autotest_MVC_2/Views/Question/GetQuestion.cshtml
@using Auto_test.Library.Models.Tickets
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model Auto_test.Library.Models.UserModels.User


@if (!Model.IsExam)
{
    <h1 class="text-center; text-light" >Bilet raqami:  <span style="color:chartreuse"> @(Model.CurrentTicketIndex + 1)</span></h1>
}

<style>
    .focus1:focus {
        transform: translateY(8px);
        background-color: blue !important
    }
    .focus1:hover {
        transform: translateY(-8px);
        background-color: yellow !important
    }
</style>


<div>
    <div>
        @{
            var startId = Model.CurrentTicket!.StarQuestionIndex;
            var questionCount = Model.CurrentTicket.QuestionsCount;
            var question = ViewBag.Question;

            Ticket ticket = Model.CurrentTicket;

            bool isAnswer = ViewBag.IsAnswer;
            TicketQuestionAnswer? questionAnswer = null;

            if (isAnswer)
            {
                questionAnswer = ViewBag.TicketAnswer;
            }

            for (int i = 0; i < questionCount; i++)
            {
                var questionIndex =  startId + i;
                var ticketAnswer = ticket.TicketAnswers!.FirstOrDefault(q => q.QuestionIndex == questionIndex);
                var bgClass = "background-color: bisque";

                if (ticketAnswer != null)
                {
                    if (questionIndex == question.Id)
                    {
                        isAnswer = true;
                        questionAnswer = ticketAnswer;
                    }

                    if (Model.IsExam)
                    {
                        bgClass = "background-color: mediumslateblue";
                    }
                    else
                    {
                        bgClass = ticketAnswer.IsCorrectAnswer ? "background-color: chartreuse" : "background-color: red";
                    }
                }
                <a class="btn btn-outline-light focus1" style="@bgClass; color: black;" asp-area=""
                   asp-controller="Question"
                   asp-action="GetQuestion"
                   asp-route-questionId="@(startId + i)"> @(i + 1) </a>
            }
        }

        <div class="d-flex align-items-center justify-content-between">      
            <div>
                @{
                    <br/>
                    <br/>
                    var imageLink = "";

                    @if (question.Media.Exist)
                    {
                        imageLink = $"/Autotest_Images/{question.Media.Name}.png";
                    }
                    else
                    {
                        imageLink = "/img/car2.jpg";
                    }

                    <img alt="Question image" src="@imageLink"/>
                    <br/>
                    <br/>
                }
            </div>

            <div class="w-25">

                @if (isAnswer && !Model.IsExam)
                {
                    <p class="btn btn-info">@question.Id. @question.Description</p>
                }

            </div>

      

            <div>
                
                @if (Model.CurrentTicket.QuestionsCount == Model.CurrentTicket.TicketAnswers!.Count)
                {
                    <div class="text-center">           

                        <a class="btn btn-info" asp-controller="Question" asp-action="Result">
                        <h2>Test natijalari</h2></a>

                        <form asp-controller="Question" asp-action="RemoveTicketAnswer">
                            <button class="btn-outline-primary btn mt-3" type="submit" style="color: aliceblue">Testni qayta bajarish</button>
                        </form>
                        
                        <form asp-controller="Question" asp-action="ShowTickets">
                            <button class="btn-outline-primary btn mt-3" type="submit" style="color: antiquewhite">Testni biletlari</button>
                        </form>

                    </div>

                }
                 
            </div>
        </div>


    </div>
    
    
    @if (Model.IsExam)
    {
        <h1 style="color: crimson; background-color: black;">@question.Question</h1>
    }
    else
    {
        <h1 style="color: crimson; background-color: black;">@question.Id. @question.Question</h1>
    }

    <br/>


    @for (int i = 0; i < question.Choices.Count; i++)
    {
        var bg = "background-color: black"; // chartreuse  //  red
        var color = "color: aliceblue";

        if (isAnswer)
        {
            if (Model.IsExam)
            {
                bg = "background-color: black";
            }
            else if (i == questionAnswer!.ChoiceIndex && !questionAnswer.IsCorrectAnswer)
            {
                bg = "background-color: red";
                color = "color: black";
            }
            else if (question.Choices[i].Answer)
            {
                bg = "background-color: chartreuse";
                color = "color: crimson";
            }

            <h5 class="btn btn-outline-info"  style="@bg; @color ">@(i + 1). @question.Choices[i].Text</h5>
            <br/>
        }
        else
        {
            <a class="btn btn-outline-info" style="background-color: black; color: aliceblue"
               asp-controller="Question" 
               asp-action="GetQuestion"
               asp-route-questionId="@question.Id" 
               asp-route-choicesIndex="@i">@(i + 1). @question.Choices[i].Text</a>
            <h5></h5>
        }
    }

</div>

Autotest_MVC_2/Views/Question/Result.cshtml
@model Auto_test.Library.Models.UserModels.User

<style>
   
    html {
        scroll-behavior: smooth;
    }

    body {
        margin: 0;
        padding: 0;
        color: white;
    }

    * {
        box-sizing: border-box;
    }

    .cards {
        background-color: rgba(0, 0, 0, 0.878);
        display: flex;
        justify-content: center;
        align-items: center;
        height: 90vh;
        padding: 0 20px;
    }

    .card {
        box-shadow: 0px 9px 50px rgba(23, 36, 65, 0.04);
        border-radius: 16px;
        background: #131e3a;
        border-top: 1px solid #d3f85a;
        padding: 20px;
    }

    .all-button {
        border: 2px solid transparent;
        background-color: #d3f85a;
        padding: 7px 25px;
        border-radius: 0 10px 0 10px;
        transition: 0.5s;
    }
    .all-button:hover {
        background-color: transparent;
        color: #d3f85a;
        border: 2px solid #d3f85a;
        transition: 0.5s;
    }

    span {
        color: #d3f85a;
    }
    .text {
        text-align: left;
    }

    .test-top {
        font-size: 30px;
        font-family: "Gill Sans", "Gill Sans MT", Calibri, "Trebuchet MS", sans-serif;
    }

    .text :nth-child(2) {
        font-size: 30px;
        margin: 0 !important;
        padding: 10px 0;
    }

    .text :nth-child(3) {
        font-size: 30px;
        margin: 0 !important;
        padding: 10px 0;
    }

    .text :nth-child(4) {
        font-size: 30px;
        margin: 0 !important;
        padding: 10px 0;
    }

    .text :nth-child(5),
    .text :nth-child(6) {
        cursor: pointer;
        display: block;
        margin: 10px 0;
        font-size: 20px;
        font-weight: bold;
    }
    .text :nth-child(6) {
        margin-top: 20px;
        border-radius: 10px 0 10px 0;
    }

</style>

@if (ViewBag.IsExam == true)
{
    if (Model.CurrentTicket!.TicketAnswers!.Count(c => c.IsCorrectAnswer) < 8)
    {
        <h1 class="btn btn-danger" style="color: azure; text-align: center; height: 40px">
            Afsuski siz autotest imtihonidan o'tolmadingiz, harakatdan to'xtamang siz albatta uddalaysiz :)
        </h1>
    }
    else
    {
        <h1 class="btn btn-info" style="color: chartreuse" >Tabriklamiz siz imtihondan o'ttingiz ;)</h1>
    }
}

<section>
    <div class="cards">
        <div class="card">
            <div class="text">
                <span class="test-top">Test Natijalari.</span>
                
                @if (ViewBag.IsExam == false)
                {
                    <h4>Bilet № : <span> @Model.CurrentTicketIndex</span></h4>
                }

                <h4>Togri javoblar soni : <span>@Model.CurrentTicket!.CorrectAnswerCount </span></h4>
                <h4>Biletlar savollar soni : <span> @Model.CurrentTicket.QuestionsCount</span></h4>
                
                @if (ViewBag.IsExam == false)
                {
                    <form asp-controller="Question" asp-action="RemoveTicketAnswer">
                        <button class="all-button" type="submit">Testni qayta bajarish</button>
                    </form>
                }

                <form asp-controller="Question" asp-action="ShowTickets">
                    <button class="all-button" type="submit">Test biletlari</button>
                </form>
                
                <form asp-controller="Question" asp-action="Exam">
                    <button class="all-button" type="submit">Imtihon topshirish</button>
                </form>
            </div>
        </div>
    </div>
</section>

Autotest_MVC_2/Views/Question/ShowTickets.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model Auto_test.Library.Models.UserModels.User


<style>

  html {
  scroll-behavior: smooth;
}

body {
  margin: 0;
  padding: 0;
  font-family: sans-serif;
  background: rgb(19, 74, 82);
  background: -moz-linear-gradient(
    90deg,
    rgba(19, 74, 82, 1) 0%,
    rgba(91, 54, 160, 1) 35%,
    rgba(58, 51, 206, 1) 63%,
    rgba(31, 100, 110, 1) 100%
  );
  background: -webkit-linear-gradient(
    90deg,
    rgba(19, 74, 82, 1) 0%,
    rgba(91, 54, 160, 1) 35%,
    rgba(58, 51, 206, 1) 63%,
    rgba(31, 100, 110, 1) 100%
  );
  background: linear-gradient(
    90deg,
    rgba(19, 74, 82, 1) 0%,
    rgba(91, 54, 160, 1) 35%,
    rgba(58, 51, 206, 1) 63%,
    rgba(31, 100, 110, 1) 100%
  );
  filter: progid:DXImageTransform.Microsoft.gradient(startColorstr="#134a52",endColorstr="#1f646e",GradientType=1);
  background-size: 100%;
}

* {
  box-sizing: border-box;
}

.start {
  text-align: center;
    background-color: transparent;
}

.start h1 {

  padding: 50px 0;
    padding-top: 10px;
  color: white;
    background-color: transparent;
  font-size: 60px;
}

.container {
  width: 1340px;
  margin: 0 auto;
  padding: 15px 0;
}

.all-button {
  font-weight: bold;
  background-color: red;
    width: 100%;
  color: black;
  border: 3px solid transparent;
  transition: 0.5s;
    
    padding: 13px 20px;
  border-radius: 20px 0 20px 0;
}
.all-button:hover {
    color: azure;
    padding: 13px 20px;
 border: 3px solid red;
  transition: 0.5s;
  cursor: pointer;
}

.cards {
  display: flex;
  flex-wrap: wrap;
  justify-content: center;
    align-items: center;
               gap: 30px;
  padding-bottom: 70px;
}

.card {
  width: 230px;
    border-radius: 20px 0 20px 0;
  overflow: hidden;
  position: relative;
  top: 0;
  left: 0;
  transition: 1s;
    margin-bottom: 20px;
  box-shadow: 2px 2px 10px 0 rgb(69, 68, 68);
}
.card:hover {
  box-shadow: 12px 12px 0 0 black;
  position: relative;
  top: 7px;
  left: 7px;
  transition: 1s;
}

.card-text {
  padding: 10px;
  text-align: center;
}
.card-text span {
  color: red;
}
.card-text button {
  width: 100%;
}

.card-text :nth-child(1) {
  margin: 5px 0;
}

.card-text :nth-child(2) {
  font-size: 20px;
  padding: 0;
  margin: 0;
}
.card img {
  width: 100%;
  height: 75px;
  object-fit: cover;
}

@@media only screen and (max-width: 1440px) {
  .container {
    width: 1140px;
    margin: 0 auto;
    padding: 15px 0;
  }
}

@@media only screen and (max-width: 900px) {
  .container {
    width: 670px !important;
    margin: 0 auto !important;
    padding: 0 15px !important;
  }
}

@@media only screen and (max-width: 1200px) and (min-width: 900px) {
  .container {
    width: 900px !important;
    margin: 0 auto !important;
    padding: 0 15px !important;
  }
}
  /*# sourceMappingURL=style.css.map */

  .all-button {
      size: A4;
      font-weight: bold;
      background-color: red;
      width: auto;
      color: antiquewhite;
      border: 3px solid transparent;
      transition: 0.5s;
    
      padding: 13px 20px;
      border-radius: 20px 0 20px 0;
  }
  .all-button:hover {
      color: black;
      padding: 13px 20px;
      border: 3px solid red;
      transition: 0.5s;
      cursor: pointer;
  }

</style>


<div class="container">

    @if (Model.ExamCurrentTicketIndex != -1)
    {
        <h1 class="start btn btn-outline-primary" style="color: antiquewhite"> Sizda yakunlanmagan imtihon testi mavjud iltimos testni oxiragacha tugating! </h1>

        <form asp-controller="Question" asp-action="Exam">
            <button type="submit" class="all-button">Imtihonga qaytish</button>
        </form>

        <div class="d-flex" style="height: -80px">

            <img src="http://themes.potenzaglobalsolutions.com/html/cardealer/revolution/assets/e13ec-06-audi-s2.png" class="w-50 imgss"/>

            <img src="http://themes.potenzaglobalsolutions.com/html/cardealer/revolution/assets/4f45e-07-bmw-s2.png"class="w-50 imgss"/>

            <!-- <img src="http://themes.potenzaglobalsolutions.com/html/cardealer/images/loader.gif" alt=""> -->

        </div>
    }
    else
    {
        <div class="d-flex" style="text-align: center" >

            <div class="start">
                <h1>Test Biletlari !</h1>
            </div>


            <div class="btn-group;  start" role="group" aria-label="Button group with nested dropdown">

                <a class="nav-link text-danger dropdown-toggle " style="color: aliceblue" data-bs-toggle="dropdown" aria-expanded="false">Savollar tilini o'zgartirish</a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" asp-controller="Question" asp-action="EditLanguage" asp-route-language="uzlotin">O'zbek</a></li>
                    <li><a class="dropdown-item" asp-controller="Question" asp-action="EditLanguage" asp-route-language="uzkiril">UzKiril</a></li>
                    <li><a class="dropdown-item" asp-controller="Question" asp-action="EditLanguage" asp-route-language="rus">Ruscha</a></li>
                </ul>

            </div>

        </div>

      

        <div class="cards">
            @foreach (var ticket in Model.UserTickets)
            {
                var bg = "";
                var isCompleted = false;

                if (ticket.TicketAnswers.Count >= 10)
                {
                    bg = "lawngreen";
                    isCompleted = true;
                }
                else
                {
                    bg = "aliceblue";
                }

                <div class="card" style="background-color:  @bg">
                    <div>
                        <img src="../img/car1.jpg"/>
                    </div>

                    <div class="card-text">
                        <h1>Bilet № <span>@(ticket.TicketIndex + 1)</span></h1>

                        @if (ticket.TicketAnswers is not null && ticket.TicketAnswers.Count > 0)
                        {
                            <h4>@ticket.CorrectAnswerCount / @ticket.QuestionsCount</h4>
                            <p>@ticket.CreateDateTime.ToString("f")</p>

                            if (isCompleted)
                            {
                                <i>Yakunlangan</i>
                            }
                            else
                            {
                                <u>Yakunlanmagan</u>
                            }
                        }

                        <form
                            asp-controller="Question"
                            asp-action="StartTicket"
                            asp-route-ticketIndex="@ticket.TicketIndex">
                            <button type="submit" class="all-button">Start</button>
                        </form>

                    </div>
                </div>
            }
        </div>
    }

</div>