Autotest_MVC_2/Controllers/HomeController.cs
using Autotest_MVC_2.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Autotest_MVC_2.Services.QuestionServices;

namespace Autotest_MVC_2.Controllers;

public class HomeController : Controller
{
    private readonly QuestionService _questionService;

    public HomeController(QuestionService questionService)
    {
        _questionService = questionService;
    }

    public IActionResult Index(string language = "uzlotin")
    {
        return View();
    }


    public IActionResult About()
    {
        return View();
    }

    public IActionResult IsRegister()
    {
        return View();
    }


    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Autotest_MVC_2/Controllers/RegistrationController.cs
using Auto_test.Library.Models.Tickets;
using Auto_test.Library.Models.UserModels;
using Autotest_MVC_2.Services.QuestionServices;
using Autotest_MVC_2.Services.UserServices;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Autotest_MVC_2.Controllers;

public class RegistrationController : Controller
{
    private readonly UserService _userService;
    private readonly QuestionService _questionService;

    public RegistrationController(UserService userService, QuestionService questionService)
    {
        _userService = userService;
        _questionService = questionService;
    }

    [HttpGet]
    public IActionResult SignUp()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> SignUp(SignUpUserModel signUpUserModel)
    {
        if (!ModelState.IsValid)
        {
            return View(signUpUserModel);
        }

        var email = _userService.DbContext.AllUsers.FirstOrDefault(u => u.UserEmailOrPhone == signUpUserModel.UserEmailOrPhone);

        var userName = _userService.DbContext.AllUsers.FirstOrDefault(u => u.UserName == signUpUserModel.UserName);


        if (userName != null && email != null)
        {
            ViewBag.UserNameHas = true;
            ViewBag.UserEmail = true;

            TempData["UserNameHas"] = true;
            TempData["UserEmail"] = true;

            return RedirectToAction(nameof(SignUp));
        }

        if (email != null)
        {
            ViewBag.UserEmail = true;

            TempData["UserEmail"] = true;
            return RedirectToAction(nameof(SignUp));
        }

        if (userName != null)
        {
            ViewBag.UserNameHas = true;
            TempData["UserNameHas"] = true;
            return RedirectToAction(nameof(SignUp));
        }

        ViewBag.UserNameHas = false;
        ViewBag.UserEmail = false;

        var user = new User()
        {
            UserId = Guid.NewGuid().ToString(),
            UserName = signUpUserModel.UserName,
            Language = "uzlotin",
            UserEmailOrPhone = signUpUserModel.UserEmailOrPhone,
            UserPassword = signUpUserModel.UserPassword,
            ImagePath = await SavePhotoPathAsync(signUpUserModel.ImagePath),
            IsExam = false,
            ExamCurrentTicketIndex = -1,
            UserTickets = new List<Ticket>(),
        };

        CreateUserTickets(user);

        HttpContext.Session.SetString("UserId", user.UserId);

        _userService.DbContext.AllUsers!.Add(user);
        _userService.DbContext.SaveChanges();

        return RedirectToAction("Index", "Home");
    }

    private void CreateUserTickets(User user)
    {
        var questionCount = _questionService.QuestionCount;
        var ticketCount = _questionService.TicketCount;

        for (var i = 0; i < ticketCount; i++)
        {
            var startIndex = i * questionCount + 1;

            user.UserTickets!.Add(new Ticket()
            {
                TicketIndex = i,
                CurrentQuestionIndex = startIndex,
                StarQuestionIndex = startIndex,
                QuestionsCount = questionCount
            });
        }
    }

    public async Task<string> SavePhotoPathAsync(IFormFile? ifFormFile)
    {
        var directoryPath = Path.Combine("wwwroot", "UserImages");

        if (!Directory.Exists(directoryPath))
            Directory.CreateDirectory(directoryPath);

        if (ifFormFile == null)
            return $"{Path.Combine("\\UserImages", "nophoto2.jpeg")}";

        var fileName = Guid.NewGuid() + ".jpg";

        using (MemoryStream ms = new())
        {
            await ifFormFile.CopyToAsync(ms);

            var photoPath = Path.Combine("wwwroot\\UserImages", fileName);

            await System.IO.File.WriteAllBytesAsync(photoPath, ms.ToArray());
        }

        return Path.Combine("\\UserImages", fileName);
    }

    [HttpGet]
    public IActionResult SignIn()
    {
        return View();
    }

    [HttpPost]
    public IActionResult SignIn(SignInUserModel signInUserModel)
    {
        var user = _userService.DbContext.AllUsers!.FirstOrDefault(
            u => u.UserEmailOrPhone == signInUserModel.UserEmailOrPhone
            && u.UserPassword == signInUserModel.UserPassword);

        if (user == null)
            return RedirectToAction(nameof(SignUp));

        var userId = UserService.UserIdCookieKey;

        HttpContext.Session.SetString(userId, user.UserId!);

        return RedirectToAction("Profile", "User");
    }

    public IActionResult CheckHasUser(bool check = true)
    {
        ViewBag.CheckHasUser = check;
        return View();
    }

    [HttpGet]
    public async Task<IActionResult> Update(SignInUserModel signInUserModel)
    {
        var isHasUser = await _userService.DbContext.AllUsers!.AnyAsync(
            u => u.UserEmailOrPhone == signInUserModel.UserEmailOrPhone
                 && u.UserPassword == signInUserModel.UserPassword);

        if (isHasUser)
        {
            return View();
        }

        return RedirectToAction(nameof(CheckHasUser), new { check = false });
    }

    [HttpPost]
    public async Task<IActionResult> Update(SignUpUserModel signInUserModel)
    {
        var user = _userService.GetCurrentUser(HttpContext);

        if (user == null)
            return RedirectToAction(nameof(CheckHasUser));

        user.UserId = user.UserId;
        user.ImagePath = await SavePhotoPathAsync(signInUserModel.ImagePath);
        user.UserName = signInUserModel.UserName;
        user.UserEmailOrPhone = signInUserModel.UserEmailOrPhone;
        user.UserPassword = signInUserModel.UserPassword;

        _userService.DbContext.SaveChanges();

        ViewBag.Message = false;

        return RedirectToAction("Profile", "User");
    }


    public IActionResult LogOut()
    {
        const string userId = UserService.UserIdCookieKey;
        HttpContext.Session.Remove(userId);
        HttpContext.Response.Cookies.Delete(userId);
        return RedirectToAction("SignIn");
    }

}

Autotest_MVC_2/Views/Home/About.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<style>
    .colorr{
        color: crimson;
        text-align: center;
    }
    .color1 {
        color: aliceblue;
        text-align: center;
    }
</style>

<h1 class="colorr btn-outline-primary" style="color: aliceblue"><span style="color: lawngreen"> Assalomu alaykum </span></h1>
<br/>
<br/>


<h2 class="colorr" style="color: aliceblue"><span style="color: crimson"> AUTOTEST_ASR </span> ga xush kelibsiz! biz sizni saytimizda ko'rishdan xursandmiz! </h2>
<br/>
<br/>

<h2 class="colorr" style="color: aliceblue">Ushbu dastur Ilmhub IT school talabasi  <span style="color: chartreuse"> Sardorbek Akhmedov Ruziboy O'g'li</span> 
    tomonidan ustozimiz <span style="color: chartreuse"> Javlonbek Fattoyev </span>  yordami bilan yozildi, ushbu dastur <span style="color: red"> 19.04.2023 </span>  da yozib tugatildi. </h2>
<br/>
<br/>

<h3 class="color1"> Ushbu saytimiz orqali siz yo'l harakati qoidalariga oid bilim va ko‘nikmalaringizni sinab ko‘rishingiz mumkin.</h3>
    
    
<h4 class="color1"> Saytimizda umumiy test savollari <span style="color: gold">  " 700 " </span> ta, 
    test biletlari soni <span style="color: gold">  " 70 " </span> ta va har biletda <span style="color: gold">  " 10 " </span> ta dan savol mavjud siz ushbu biletlarni bajarganingizdan so'ng 
   <span style="color: chartreuse">  " TEST IMTIHONI " </span>bo'limiga o'tib  yo'l harakati qoidalarini qay darajada o'zlashtirganingizni imtihon orqali bilib olishingiz mumkin.</h4>
    
<br/>

<div class="d-flex">
    <img
        src="http://themes.potenzaglobalsolutions.com/html/cardealer/revolution/assets/e13ec-06-audi-s2.png"
        alt=""
        class="w-50 imgss"/>
    <img
        src="http://themes.potenzaglobalsolutions.com/html/cardealer/revolution/assets/4f45e-07-bmw-s2.png"
        alt=""
        class="w-50 imgss"/>

    <!-- <img src="http://themes.potenzaglobalsolutions.com/html/cardealer/images/loader.gif" alt=""> -->
</div>

Autotest_MVC_2/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<style>
    .colorr{
        color: crimson;
        text-align: center;
    }
    .color1 {
        color: aliceblue;
        text-align: center;
    }
</style>


<h1>

    <a style="text-size-adjust: auto; text-align: center" href="https://github.com/pattisoj">
        <img alt="Typing SVG"src="https://readme-typing-svg.herokuapp.com?font=IBM+Plex+Sans&size=25&duration=4500&color=BCB1F7&center=true&width=500&lines=Assalomu+alaykum👋;
AUTOTEST_ASR;
Biz sizni saytimizda ko'rishdan xursandmiz!"/>
    </a>
</h1>


<h1 class="colorr btn-outline-primary" style="color: aliceblue"><span style="color: lawngreen"> Assalomu alaykum </span></h1>
<br/>
<br/>


<h2 class="colorr" style="color: aliceblue"><span style="color: crimson"> AUTOTEST_ASR </span> ga xush kelibsiz! biz sizni saytimizda ko'rishdan Xursandmiz! </h2>
<br/>
<br/>

<h3 class="color1"> Ushbu saytimiz orqali siz yo'l harakati qoidalariga oid bilim va ko‘nikmalaringizni sinab ko‘rishingiz mumkin.</h3>
    
    
<h4 class="color1"> Saytimizda umumiy test savollari <span style="color: gold">  " 700 " </span> ta, 
    test biletlari soni <span style="color: gold">  " 70 " </span> ta va har biletda <span style="color: gold">  " 10 " </span> ta dan savol mavjud siz ushbu biletlarni bajarganingizdan so'ng 
   <span style="color: crimson">  " TEST IMTIHONI " </span>bo'limiga o'tib  yo'l harakati qoidalarini qay darajada o'zlashtirganingizni imtihon orqali bilib olishingiz mumkin.</h4>
    
<br/>

<div class="d-flex">
    <img
        src="http://themes.potenzaglobalsolutions.com/html/cardealer/revolution/assets/e13ec-06-audi-s2.png"
        alt=""
        class="w-50 imgss"/>
    <img
        src="http://themes.potenzaglobalsolutions.com/html/cardealer/revolution/assets/4f45e-07-bmw-s2.png"
        alt=""
        class="w-50 imgss"/>

    <!-- <img src="http://themes.potenzaglobalsolutions.com/html/cardealer/images/loader.gif" alt=""> -->
</div>

Autotest_MVC_2/Views/Home/IsRegister.cshtml
@{
    ViewData["Title"] = "Home Page";
}


<style>

    .colorr{
        color: crimson;
        text-align: center;
    }
    .color1 {
        color: aliceblue;
        text-align: center;
    }

    .all-button {
        margin: 30px 0;
        font-weight: bold;
        background-color: yellow;
        color: black;
        border: 2px solid transparent;
        transition: 0.5s;
        font-size: 20px;
        padding: 13px 20px;
        border-radius: 20px 0 20px 0;
    }

    .all-button:hover {
        background-color: transparent;
        color: whitesmoke;
        border: 2px solid yellow;
        transition: 0.5s;
    }
    
</style>




<h2 class="colorr btn-outline-primary" style="color: aliceblue"><span style="color: crimson">
     Dasturdan foydalanish uchun iltimos ro'yxatdan o'ting yoki tizimga kiring
</span> </h2>
<br/>
<br/>


<a class="all-button"style="color: crimson; text-decoration: none; " asp-area="" asp-controller="Registration" asp-action="SignIn">Tizimga kirish</a>
<h1></h1>
<h1></h1>
<br/>
<br/>
<a class="all-button"style="color: crimson; text-decoration: none; " asp-area="" asp-controller="Registration" asp-action="SignUp">  Ro'yxatdan o'tish</a>


<div class="d-flex">
    <img
        src="http://themes.potenzaglobalsolutions.com/html/cardealer/revolution/assets/e13ec-06-audi-s2.png"
        alt=""
        class="w-50 imgss"/>
    <img
        src="http://themes.potenzaglobalsolutions.com/html/cardealer/revolution/assets/4f45e-07-bmw-s2.png"
        alt=""
        class="w-50 imgss"/>

    <!-- <img src="http://themes.potenzaglobalsolutions.com/html/cardealer/images/loader.gif" alt=""> -->
</div>